Fix searchString missing type (#1714)
This fix the typescript error:

Type 'Query' is not assignable to type 'string'.

Detail:
src/index.ts:76:13 - error TS2322: Type 'string | Query | string[] | Query[]' is not assignable to type 'string | null | undefined'.
  Type 'Query' is not assignable to type 'string'.

76             contains: searchString,
               ~~~~~~~~
src/index.ts:81:13 - error TS2322: Type 'string | Query | string[] | Query[]' is not assignable to type 'string | null | undefined'.
  Type 'Query' is not assignable to type 'string'.

81             contains: searchString,
               ~~~~~~~~

`contains: <string>searchString` or `contains: searchString as string` are also possible solutions but less cleaner.